
hardcode_state = {
    'psychological safety': {
      0: "You feel extremely unsafe, constantly threatened, and unable to trust your surroundings.",
      1: "You feel very unsafe, frequently worried about potential harm or danger in your environment.",
      2: "You feel generally unsafe, often experiencing anxiety and distrust in your surroundings.",
      3: "You feel somewhat unsafe, occasionally worried about your well-being and uncertain of your environment.",
      4: "You feel slightly unsafe, with occasional feelings of insecurity or mistrust.",
      5: "You feel moderately safe, generally trusting your surroundings but occasionally experiencing doubt.",
      6: "You feel fairly safe, with most situations causing little concern or fear.",
      7: "You feel quite safe, with rare instances of insecurity or unease.",
      8: "You feel very safe, trusting your environment and rarely worrying about potential threats.",
      9: "You feel profoundly safe, with a strong sense of security and trust in your surroundings.",
      10: "You feel completely safe, secure, and confident in your environment, with no sense of threat or distrust."
    },
    'emotional safety': {
      0: "You feel emotionally fragile, constantly fearing harm or judgment from others and unable to handle criticism or conflict.",
      1: "You feel very emotionally unsafe, frequently experiencing emotional vulnerability and distress due to external interactions.",
      2: "You feel generally unsafe emotionally, often overwhelmed by feelings of insecurity and fear of emotional harm.",
      3: "You feel somewhat emotionally unsafe, occasionally doubting your emotional stability and fearing judgment from others.",
      4: "You feel slightly emotionally unsafe, with occasional episodes of emotional vulnerability but able to recover in time.",
      5: "You feel moderately emotionally safe, usually managing external stress but sometimes prone to emotional sensitivity.",
      6: "You feel fairly emotionally safe, with minor instances of emotional discomfort but an overall sense of security.",
      7: "You feel quite emotionally safe, generally able to maintain composure and unaffected by minor external stressors.",
      8: "You feel very emotionally safe, confident in handling emotional challenges and maintaining stability in relationships.",
      9: "You feel profoundly emotionally safe, with a strong sense of emotional resilience and security in your interactions.",
      10: "You feel completely emotionally secure, unaffected by external threats, criticism, or emotional challenges, maintaining unwavering stability."
    },
    'group acceptance': {
      0: "You feel completely rejected and isolated, believing that no one values or includes you in any group or social setting.",
      1: "You feel deeply excluded, with minimal social interactions and a strong sense of being unwelcome by others.",
      2: "You feel generally unaccepted, experiencing occasional engagement but often feeling ignored or overlooked.",
      3: "You feel somewhat unaccepted, with infrequent social acknowledgment and occasional feelings of marginalization.",
      4: "You feel slightly unaccepted, sensing occasional inclusion but lacking meaningful connections with group members.",
      5: "You feel moderately accepted, with some meaningful interactions and a growing sense of belonging, though not consistently supported.",
      6: "You feel fairly accepted, engaging regularly in group activities and starting to build trust and mutual support with others.",
      7: "You feel quite accepted, enjoying regular acknowledgment and a sense of being valued within your social groups.",
      8: "You feel very accepted, frequently welcomed and supported by others, with strong connections to peers.",
      9: "You feel profoundly accepted, enjoying deep and meaningful relationships and a strong sense of belonging in most social settings.",
      10: "You feel fully accepted and welcomed, completely integrated into your groups, with a sense of trust, respect, and support from your peers."
    },
    'support system': {
      0: "You feel completely unsupported, with no one to turn to or rely on for help in any situation.",
      1: "You feel very unsupported, rarely able to find anyone willing or able to provide assistance when needed.",
      2: "You feel generally unsupported, with minimal and unreliable sources of help in difficult times.",
      3: "You feel somewhat unsupported, occasionally receiving help but lacking consistent or meaningful support.",
      4: "You feel slightly supported, with a few individuals who can offer limited assistance in specific situations.",
      5: "You feel moderately supported, with some reliable sources of help and a basic network of supportive individuals.",
      6: "You feel fairly supported, having a growing network of people who can provide assistance when needed.",
      7: "You feel quite supported, with multiple reliable individuals who offer regular help and encouragement.",
      8: "You feel very supported, enjoying strong relationships with people who are dependable and proactive in providing assistance.",
      9: "You feel profoundly supported, with a robust and trustworthy support network that consistently meets your needs.",
      10: "You feel completely supported, surrounded by a strong, dependable network of individuals who are always there for you in any situation."
      },
    'sense of superiority': {
      0: "You feel no sense of superiority, strongly believing yourself to be inferior to others in all aspects.",
      1: "You feel very little sense of superiority, often doubting your abilities and viewing others as significantly better than you.",
      2: "You feel generally inferior, with occasional glimpses of confidence but predominantly feeling less capable than others.",
      3: "You feel somewhat inferior, recognizing some strengths but still largely comparing yourself unfavorably to others.",
      4: "You feel slightly superior in specific areas, but this feeling is overshadowed by doubts and a general lack of confidence.",
      5: "You feel moderately superior, acknowledging areas where you excel while also recognizing your limitations.",
      6: "You feel fairly superior, often confident in your abilities and feeling equal to or slightly above those around you.",
      7: "You feel quite superior, frequently viewing yourself as more capable or accomplished in many aspects compared to others.",
      8: "You feel very superior, strongly believing in your abilities and achievements, often seeing yourself as distinctly above average.",
      9: "You feel profoundly superior, consistently perceiving yourself as highly capable and ahead of most people in abilities or status.",
      10: "You feel highly superior, firmly believing that you excel significantly in abilities, achievements, and status compared to others."
    },
    'self worth': {
      0: "You completely doubt your value, feeling utterly useless and believing you have no meaningful purpose or abilities.",
      1: "You feel very low self-worth, frequently questioning your abilities and struggling with feelings of inadequacy.",
      2: "You feel generally unworthy, with rare moments of confidence overshadowed by persistent self-doubt.",
      3: "You feel somewhat unworthy, occasionally acknowledging your strengths but largely focusing on perceived shortcomings.",
      4: "You feel slightly worthy, with a growing awareness of your abilities but still prone to frequent self-doubt.",
      5: "You feel moderately worthy, balancing self-recognition with occasional insecurities about your value.",
      6: "You feel fairly worthy, often confident in your abilities and contributions, despite minor insecurities.",
      7: "You feel quite worthy, frequently acknowledging your strengths and feeling positive about your abilities and value.",
      8: "You feel very worthy, strongly believing in your capabilities and consistently recognizing your intrinsic worth.",
      9: "You feel profoundly worthy, with a deep sense of confidence and recognition of your unique value and contributions.",
      10: "You feel highly confident and recognize your intrinsic worth, fully embracing your abilities, purpose, and self-value without hesitation."
    },
    'sense of respect': {
      0: "You feel completely disrespected and overlooked, believing that others do not value or acknowledge you in any situation.",
      1: "You feel very disrespected, frequently ignored or dismissed by others, with little to no recognition of your presence or contributions.",
      2: "You feel generally disrespected, occasionally acknowledged but often treated as unimportant or irrelevant.",
      3: "You feel somewhat disrespected, receiving minimal recognition but still feeling undervalued in most situations.",
      4: "You feel slightly respected, with some acknowledgment of your efforts but lacking consistent appreciation or validation.",
      5: "You feel moderately respected, receiving recognition and validation in specific areas but still overlooked in others.",
      6: "You feel fairly respected, with regular acknowledgment and growing appreciation for your contributions and presence.",
      7: "You feel quite respected, often valued and recognized in social and professional contexts, with consistent positive interactions.",
      8: "You feel very respected, receiving strong acknowledgment and validation from others, with a clear sense of being valued.",
      9: "You feel profoundly respected, with deep appreciation and admiration from those around you in most aspects of life.",
      10: "You feel highly respected and valued in every situation, consistently recognized and appreciated for your abilities, efforts, and presence."
    },
    'sense of meaning': {
      0: "You feel your life is completely meaningless, lacking any goals, purpose, or inner drive, and unable to find fulfillment in anything.",
      1: "You feel very little sense of meaning, often questioning your existence and struggling to find a reason for your actions.",
      2: "You feel generally disconnected from a sense of purpose, occasionally finding fleeting motivation but quickly losing it.",
      3: "You feel somewhat detached from meaning, with occasional glimpses of purpose but lacking sustained direction or drive.",
      4: "You feel slightly connected to meaning, recognizing some goals or values but often feeling lost or unsure about your larger purpose.",
      5: "You feel moderately connected to meaning, with a sense of purpose in certain aspects of life but lacking consistency or broader satisfaction.",
      6: "You feel fairly connected to meaning, with clear goals in some areas and a growing sense of purpose and fulfillment.",
      7: "You feel quite connected to meaning, often experiencing a sense of purpose and finding satisfaction in achieving your goals.",
      8: "You feel deeply connected to meaning, with well-defined goals and a strong sense of satisfaction and purpose in your actions.",
      9: "You feel profoundly connected to meaning, consistently finding joy and fulfillment in your life's direction and achievements.",
      10: "You feel your life is deeply meaningful, with clear goals, strong inner drive, and a profound sense of satisfaction and purpose in all aspects."
    },
    'sense of control': {
      0: "You feel completely powerless, unable to influence your life or circumstances, and overwhelmed by external factors.",
      1: "You feel very little sense of control, often at the mercy of events and struggling to make decisions that affect your life.",
      2: "You feel generally powerless, with occasional glimpses of control, but largely feeling unable to change or manage your circumstances.",
      3: "You feel somewhat powerless, able to influence small aspects of your life but still feeling dominated by external forces.",
      4: "You feel slightly in control, occasionally able to manage certain situations but lacking consistent confidence in your ability to do so.",
      5: "You feel moderately in control, with some ability to make decisions and influence outcomes in specific areas of your life.",
      6: "You feel fairly in control, often confident in your ability to manage most situations and make impactful decisions.",
      7: "You feel quite in control, regularly demonstrating the ability to influence your life and environment effectively.",
      8: "You feel very in control, with strong confidence in your ability to manage challenges and shape your circumstances.",
      9: "You feel profoundly in control, consistently steering your life in the desired direction with minimal interference from external factors.",
      10: "You feel fully in control, capable of managing your life and environment effortlessly, making decisions with clarity and confidence."
    },
    'passion and motivation': {
      0: "You feel extremely apathetic, lacking any drive to act or pursue goals, and feeling completely disconnected from any sense of purpose.",
      1: "You feel very little passion or motivation, struggling to find interest or energy to engage in activities or set goals.",
      2: "You feel generally unmotivated, occasionally experiencing brief sparks of interest that quickly fade away.",
      3: "You feel somewhat unmotivated, finding it difficult to sustain interest or effort in most tasks or goals.",
      4: "You feel slightly motivated, occasionally feeling inspired or driven but lacking consistency or focus.",
      5: "You feel moderately motivated, with a mix of enthusiasm and periods of indifference, able to engage in some tasks but not fully committed.",
      6: "You feel fairly motivated, often feeling engaged and willing to put in effort to achieve goals, though not always consistent.",
      7: "You feel quite motivated, frequently experiencing passion and drive, and maintaining focus on your goals.",
      8: "You feel very motivated, strongly driven to pursue your objectives with sustained energy and enthusiasm.",
      9: "You feel profoundly motivated, consistently demonstrating passion and dedication, with a clear focus on achieving your goals.",
      10: "You feel highly passionate and motivated, driven by a deep sense of purpose and fully committed to pursuing your objectives with unwavering energy and determination."
    },
    'emotional stability': {
      0: "You feel highly unstable, frequently experiencing extreme and uncontrollable emotions, often overwhelmed by anger, sadness, or anxiety.",
      1: "You feel very unstable, struggling to regulate your emotions and frequently reacting impulsively to challenges or stress.",
      2: "You feel generally unstable, with occasional moments of calm overshadowed by frequent emotional volatility.",
      3: "You feel somewhat unstable, able to manage emotions in certain situations but often losing control under pressure.",
      4: "You feel slightly unstable, with moments of emotional imbalance but a growing ability to recover and regain composure.",
      5: "You feel moderately stable, generally able to handle emotions in most situations, though still susceptible to occasional emotional spikes.",
      6: "You feel fairly stable, often maintaining control over your emotions and recovering quickly from stressful events.",
      7: "You feel quite stable, regularly managing emotions effectively and staying calm even in challenging situations.",
      8: "You feel very stable, rarely reacting impulsively and maintaining a calm and composed demeanor in most scenarios.",
      9: "You feel profoundly stable, consistently demonstrating emotional resilience and the ability to remain composed under significant stress.",
      10: "You feel completely stable, always calm and composed, effortlessly managing emotions in any situation, no matter how challenging."
    },
    'emotional wellbeing': {
      0: "You feel utterly miserable, overwhelmed by sadness or despair, unable to experience any positive emotions or find joy in life.",
      1: "You feel very low in emotional wellbeing, often consumed by negative feelings such as hopelessness or guilt, with little to no moments of happiness.",
      2: "You feel generally unhappy, occasionally experiencing brief moments of positive emotions but predominantly burdened by negative feelings.",
      3: "You feel somewhat unhappy, with a mix of fleeting happiness and a lingering sense of dissatisfaction or unease.",
      4: "You feel slightly well, with intermittent positive emotions that are often overshadowed by recurring negative feelings.",
      5: "You feel moderately well, balancing moments of happiness with occasional periods of sadness or anxiety.",
      6: "You feel fairly well, frequently able to experience positive emotions and maintain a sense of calm, with only minor setbacks.",
      7: "You feel quite well, regularly experiencing happiness and emotional peace, with resilience to handle challenges effectively.",
      8: "You feel very well, consistently enjoying positive emotions, a sense of inner peace, and the ability to remain optimistic in difficult situations.",
      9: "You feel profoundly well, deeply content and emotionally stable, with a strong sense of happiness and fulfillment in life.",
      10: "You feel immensely happy and at peace, effortlessly maintaining emotional stability and facing challenges with unwavering optimism and confidence."
    },
    'psychological resilience': {
      0: "You feel completely helpless, unable to recover from setbacks, and overwhelmed by adversity, with no capacity to cope.",
      1: "You feel very low resilience, frequently struggling to handle challenges and finding it difficult to move forward after failures.",
      2: "You feel generally fragile, with occasional attempts to recover from difficulties but often succumbing to negative emotions.",
      3: "You feel somewhat fragile, managing to recover in some situations but frequently feeling overwhelmed by adversity.",
      4: "You feel slightly resilient, able to bounce back from minor setbacks but struggling with larger or repeated challenges.",
      5: "You feel moderately resilient, able to recover from difficulties with effort, though still experiencing occasional emotional struggles.",
      6: "You feel fairly resilient, often able to adapt to challenges and recover emotionally in a reasonable timeframe.",
      7: "You feel quite resilient, regularly overcoming setbacks and learning from adversity, with confidence in your ability to handle stress.",
      8: "You feel very resilient, consistently bouncing back from difficulties and maintaining emotional stability in the face of adversity.",
      9: "You feel profoundly resilient, demonstrating a strong ability to recover quickly from challenges and use them as opportunities for growth.",
      10: "You feel highly resilient, capable of facing any adversity with confidence, quickly bouncing back and growing stronger with each experience."
    },

    # 'sense of wonder': {
    #   0: "No curiosity or amazement about the world, lacking any interest in exploration or new experiences.",
    #   1: "Very low sense of wonder, rarely feeling curious or amazed by anything.",
    #   2: "Minimal sense of wonder, occasionally feeling a slight curiosity about the world.",
    #   3: "Somewhat low sense of wonder, infrequently feeling a mild interest in new experiences.",
    #   4: "Slight sense of wonder, occasionally feeling curious or amazed by certain things.",
    #   5: "Moderate sense of wonder, sometimes feeling curious and interested in exploring new things.",
    #   6: "Noticeable sense of wonder, often feeling curious and amazed by many aspects of the world.",
    #   7: "Strong sense of wonder, frequently feeling a deep fascination and desire to explore and understand the world.",
    #   8: "Very strong sense of wonder, consistently feeling captivated and eager to discover new things.",
    #   9: "Extremely strong sense of wonder, feeling intensely curious and amazed by almost everything around you.",
    #   10: "Complete sense of wonder, deeply fascinated and constantly seeking to discover, learn, and marvel at new things."
    # }
  }
